name: seeft_mobile
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.17.0'
  flutter: '>=2.10.0'
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  go_router: ^5.0.3
  google_fonts: ^3.0.1
  hooks_riverpod: ^1.0.4
  http: ^0.13.5
  meta: ^1.8.0
  simple_logger: ^1.9.0+1
dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  go_router_builder: ^2.0.0
  image_test_utils:
    git:
      url: https://github.com/mono0926/image_test_utils.git
      ref: add-compressionState
  json_serializable: ^6.4.1
  mockito:
  pedantic_mono:
flutter:
  uses-material-design: true
